### ISSUE TITLE
ASReview crashes with log file of different dataset.

### ISSUE THREAD

**Issue by qubixes** [msdslab/automated-systematic-review#128]

**Comment by GerbrichFerdinands** [comment]
I think I ran into this problem as well: 

<img width="695" alt="Screenshot 2019-11-19 at 23 43 50" src="https://user-images.githubusercontent.com/45358236/69792625-427eed00-11c7-11ea-877f-b6e77f425aa1.png">

I found the resulting error message quite confusing and it took me a while to figure out that the fact that I was recycling an already existing log file was the cause of the problem. Is it possible to include a more clear error message?

**Comment by J535D165** [comment]
Is this an issue with reading the dataset from the datasets repo? Internet connection problems? Check #107
