### ISSUE TITLE
ASReview regards empty abstracts as relevant. 

### ISSUE THREAD

**Issue by GerbrichFerdinands** [msdslab/automated-systematic-review#137]
In my .csv export file, the most relevant (unreviewed) abstracts are the ones that are empty (see screenshot below). 

To me this seems like ASReview thinks less text = better? 
However, the papers I get presented with by ASReview are  (in general) not the empty ones.
Maybe something goes wrong in the ` Export` option.

<img width="1101" alt="image" src="https://user-images.githubusercontent.com/45358236/69324404-ad20ad80-0c48-11ea-9ada-db9abeb4e314.png">

**Comment by qubixes** [comment]
I'll check the code to see if there's a bug in the export function.
