### ISSUE TITLE
Automated testing of docs rendering process

### ISSUE THREAD

**Issue by J535D165** [msdslab/automated-systematic-review#141]
We would like to add a job to our CI pipeline that tests the rendering of our docs (on ReadTheDocs)

Two steps:

- [ ] Create empty virtualenv (to test our mocked libs)
- [ ] Build docs

**Comment by J535D165** [comment]
@jelletreep Interested?

**Comment by jelletreep** [comment]
Interested, but not sure how much work it will be and when I will be able to do this. When do you need it up and running? In the week of 2 december I definitely have time to work on this issue.
