### ISSUE TITLE
 Improved logging for AL

### ISSUE THREAD

**Issue by J535D165** [msdslab/automated-systematic-review#30]
## Logger

General parameters

- [ ] experiment name
- [x] model parameters
- [x] model fitting parameters
- [ ] experiment name
- [x] start datetime and end datetime
- [ ] name of the embedding matrix

What we can include for each iteration:

- [x] indices and labels of the train data
- [x] probs of the pool
- [x] label prediction for the pool
- [ ] time
- [ ] model parameters

## Log parsing

To do

**Comment by qubixes** [comment]
I'll have a pull request coming up for the label prediction for the pool.
