### ISSUE TITLE
Performance: prediction is done twice

### ISSUE THREAD

**Issue by qubixes** [msdslab/automated-systematic-review#32]
The modAL library uses the predict_proba function on all samples for uncertainty sampling, to learn which items should be queried next. For our simulation, we would like to know how good our current predictions are (to compare improvement), so we're also using some predict* function to do that, resulting in double work. Since the prediction is the most time consuming part of the simulation, removing this double work would result in a significant speedup. 

The modAL library doesn't really expose the predict_proba result (it is almost immediately thrown away). Perhaps the best (short term) solution is to (re)code the uncertainty sampling in a way that it saves the prediction result to a list?

**Comment by J535D165** [comment]
Fixed in #35
