### ISSUE TITLE
UnboundLocalError

### ISSUE THREAD

**Issue by rpool** [msdslab/automated-systematic-review#55]
Hi all,
When running in oracle mode, I encounter an "UnboundLocalError". It seems that indeed the data variable is not set in review.py. What does this data structure have to filled with?

Command line: "asr oracle ../../schoot-lgmm-ptsd.csv "
Screen output:
Using lstm_base model
Start review in 'oracle' mode.
Prepare dataset.

                (  )   (   )  )
                 ) (   )  (  (
                 ( )  (    ) )
                 _____________
                <_____________> ___
                |             |/ _ \ 
                |               | | |
                |               |_| |
             ___|             |\___/
            /    \___________/    \ 
            \_____________________/

Reading 2000000 vectors with 300 dimensions.
Found 17080 word vectors.
Creating matrix with 20000 vectors with dimension 300.
Shape of embedding matrix:  (20001, 300)
Using class weights: 0 <- 1.0, 1 <- 30.0
Query strategy: Least confidence / Uncertainty sampling
Using all training data method to obtain training data.
Are there papers you definitively want to include?
Give the indices of these papers. Separate them with spaces.
Include: 219 261
Are there papers you definitively want to exclude?
Give the indices of these papers. Separate them with spaces.
Exclude: 1 2
Traceback (most recent call last):
  File "/usr/local/r.pool/anaconda3/bin/asr", line 10, in <module>
    sys.exit(main())
  File "/usr/local/r.pool/anaconda3/lib/python3.7/site-packages/asr/__main__.py", line 167, in main
    _review_oracle()
  File "/usr/local/r.pool/anaconda3/lib/python3.7/site-packages/asr/__main__.py", line 148, in _review_oracle
    review_oracle(path, **args_dict)
  File "/usr/local/r.pool/anaconda3/lib/python3.7/site-packages/asr/review.py", line 264, in review_oracle
    review(dataset, mode='oracle', **kwargs)
  File "/usr/local/r.pool/anaconda3/lib/python3.7/site-packages/asr/review.py", line 227, in review
    data,
UnboundLocalError: local variable 'data' referenced before assignment

**Comment by qubixes** [comment]
Hi,

I’m pretty sure this problem is fixed in the latest code (see pull request), but it hasn’t been merged yet with the master branch. I’ll contact Jonathan to get it merged in some form or another. In the meantime you could try to checkout the « API-fix » branch of my repo.

**Comment by rpool** [comment]
Hi qubixes,
Thanks, the API-fix branch works indeed, thanks!

**Comment by J535D165** [comment]
Closed in #53. Thanks Rene for reporting.
