### ISSUE TITLE
Package requires newer setup tools

### ISSUE THREAD

**Issue by eduh** [msdslab/automated-systematic-review#60]
Python 3.7.3 on windows includes  setuptools 40.8.0 which is too low for some tenserflow components.
Before installing the package run
%>pip install -U setuptools
This will install setuptools 41.0.0 so the install runs smoothly.

**Comment by J535D165** [comment]
Thanks @eduh 

For future reference: Solve this issue by upgrading setuptools with  `pip install --upgrade setuptools>=41.0.0`
